version: '3'
services:
  webapp:
    build: .
    ports:
      - "5000:5000"
    networks:
      - monitoring-net
      
  prometheus:
    image: prom/prometheus:v2.30.3
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring-net

networks:
  monitoring-net:
